### ISSUE TITLE
Support OpenGL 2.0

### ISSUE THREAD

**Issue by Fleker** [PureNexus/android_device_google_molly#1]
Tried using Google Maps API in an app. It was working well on Lollipop, but I ran into this error when trying on the flashed version.

    12-28 01:10:18.439 24685-24685/com.felkertech.n.weatherdelta I/Google Maps Android API: Google Play services client version: 8298000
    12-28 01:10:18.442 24685-24685/com.felkertech.n.weatherdelta I/Google Maps Android API: Google Play services package version: 8487836
    12-28 01:10:18.527 24685-24685/com.felkertech.n.weatherdelta E/Google Maps Android API: Google Maps Android API v2 only supports devices with OpenGL ES 2.0 and above

It seems like OpenGL is either broken or not stated to be supported. Is this an easy fix?

**Comment by dhacker29** [comment]
https://github.com/PureNexus/android_device_google_molly/commit/28c3ce8e8fbd918e667a13238789e1dec28f0259

This should fix it.  You can try manually editing your build.prop
